
/* ############################################################# */
/* ### Copyright © 2026 Maxim Rysevets. All rights reserved. ### */
/* ############################################################# */

import Foundation

extension Date {

    static public let TIME_ZONES_OFFSSET: [String: Int] = [
        "Africa/Abidjan": 0,
        "Africa/Accra": 0,
        "Africa/Addis_Ababa": 10800,
        "Africa/Algiers": 3600,
        "Africa/Asmara": 10800,
        "Africa/Bamako": 0,
        "Africa/Bangui": 3600,
        "Africa/Banjul": 0,
        "Africa/Bissau": 0,
        "Africa/Blantyre": 7200,
        "Africa/Brazzaville": 3600,
        "Africa/Bujumbura": 7200,
        "Africa/Cairo": 10800,
        "Africa/Casablanca": 3600,
        "Africa/Ceuta": 7200,
        "Africa/Conakry": 0,
        "Africa/Dakar": 0,
        "Africa/Dar_es_Salaam": 10800,
        "Africa/Djibouti": 10800,
        "Africa/Douala": 3600,
        "Africa/El_Aaiun": 3600,
        "Africa/Freetown": 0,
        "Africa/Gaborone": 7200,
        "Africa/Harare": 7200,
        "Africa/Johannesburg": 7200,
        "Africa/Juba": 7200,
        "Africa/Kampala": 10800,
        "Africa/Khartoum": 7200,
        "Africa/Kigali": 7200,
        "Africa/Kinshasa": 3600,
        "Africa/Lagos": 3600,
        "Africa/Libreville": 3600,
        "Africa/Lome": 0,
        "Africa/Luanda": 3600,
        "Africa/Lubumbashi": 7200,
        "Africa/Lusaka": 7200,
        "Africa/Malabo": 3600,
        "Africa/Maputo": 7200,
        "Africa/Maseru": 7200,
        "Africa/Mbabane": 7200,
        "Africa/Mogadishu": 10800,
        "Africa/Monrovia": 0,
        "Africa/Nairobi": 10800,
        "Africa/Ndjamena": 3600,
        "Africa/Niamey": 3600,
        "Africa/Nouakchott": 0,
        "Africa/Ouagadougou": 0,
        "Africa/Porto-Novo": 3600,
        "Africa/Sao_Tome": 0,
        "Africa/Tripoli": 7200,
        "Africa/Tunis": 3600,
        "Africa/Windhoek": 7200,
        "America/Adak": -32400,
        "America/Anchorage": -28800,
        "America/Anguilla": -14400,
        "America/Antigua": -14400,
        "America/Araguaina": -10800,
        "America/Argentina/Buenos_Aires": -10800,
        "America/Argentina/Catamarca": -10800,
        "America/Argentina/Cordoba": -10800,
        "America/Argentina/Jujuy": -10800,
        "America/Argentina/La_Rioja": -10800,
        "America/Argentina/Mendoza": -10800,
        "America/Argentina/Rio_Gallegos": -10800,
        "America/Argentina/Salta": -10800,
        "America/Argentina/San_Juan": -10800,
        "America/Argentina/San_Luis": -10800,
        "America/Argentina/Tucuman": -10800,
        "America/Argentina/Ushuaia": -10800,
        "America/Aruba": -14400,
        "America/Asuncion": -10800,
        "America/Atikokan": -18000,
        "America/Bahia_Banderas": -21600,
        "America/Bahia": -10800,
        "America/Barbados": -14400,
        "America/Belem": -10800,
        "America/Belize": -21600,
        "America/Blanc-Sablon": -14400,
        "America/Boa_Vista": -14400,
        "America/Bogota": -18000,
        "America/Boise": -21600,
        "America/Cambridge_Bay": -21600,
        "America/Campo_Grande": -14400,
        "America/Cancun": -18000,
        "America/Caracas": -14400,
        "America/Cayenne": -10800,
        "America/Cayman": -18000,
        "America/Chicago": -18000,
        "America/Chihuahua": -21600,
        "America/Ciudad_Juarez": -21600,
        "America/Costa_Rica": -21600,
        "America/Coyhaique": -10800,
        "America/Creston": -25200,
        "America/Cuiaba": -14400,
        "America/Curacao": -14400,
        "America/Danmarkshavn": 0,
        "America/Dawson_Creek": -25200,
        "America/Dawson": -25200,
        "America/Denver": -21600,
        "America/Detroit": -14400,
        "America/Dominica": -14400,
        "America/Edmonton": -21600,
        "America/Eirunepe": -18000,
        "America/El_Salvador": -21600,
        "America/Fort_Nelson": -25200,
        "America/Fortaleza": -10800,
        "America/Glace_Bay": -10800,
        "America/Goose_Bay": -10800,
        "America/Grand_Turk": -14400,
        "America/Grenada": -14400,
        "America/Guadeloupe": -14400,
        "America/Guatemala": -21600,
        "America/Guayaquil": -18000,
        "America/Guyana": -14400,
        "America/Halifax": -10800,
        "America/Havana": -14400,
        "America/Hermosillo": -25200,
        "America/Indiana/Indianapolis": -14400,
        "America/Indiana/Knox": -18000,
        "America/Indiana/Marengo": -14400,
        "America/Indiana/Petersburg": -14400,
        "America/Indiana/Tell_City": -18000,
        "America/Indiana/Vevay": -14400,
        "America/Indiana/Vincennes": -14400,
        "America/Indiana/Winamac": -14400,
        "America/Inuvik": -21600,
        "America/Iqaluit": -14400,
        "America/Jamaica": -18000,
        "America/Juneau": -28800,
        "America/Kentucky/Louisville": -14400,
        "America/Kentucky/Monticello": -14400,
        "America/Kralendijk": -14400,
        "America/La_Paz": -14400,
        "America/Lima": -18000,
        "America/Los_Angeles": -25200,
        "America/Lower_Princes": -14400,
        "America/Maceio": -10800,
        "America/Managua": -21600,
        "America/Manaus": -14400,
        "America/Marigot": -14400,
        "America/Martinique": -14400,
        "America/Matamoros": -18000,
        "America/Mazatlan": -25200,
        "America/Menominee": -18000,
        "America/Merida": -21600,
        "America/Metlakatla": -28800,
        "America/Mexico_City": -21600,
        "America/Miquelon": -7200,
        "America/Moncton": -10800,
        "America/Monterrey": -21600,
        "America/Montevideo": -10800,
        "America/Montserrat": -14400,
        "America/Nassau": -14400,
        "America/New_York": -14400,
        "America/Nome": -28800,
        "America/Noronha": -7200,
        "America/North_Dakota/Beulah": -18000,
        "America/North_Dakota/Center": -18000,
        "America/North_Dakota/New_Salem": -18000,
        "America/Nuuk": -3600,
        "America/Ojinaga": -18000,
        "America/Panama": -18000,
        "America/Paramaribo": -10800,
        "America/Phoenix": -25200,
        "America/Port_of_Spain": -14400,
        "America/Port-au-Prince": -14400,
        "America/Porto_Velho": -14400,
        "America/Puerto_Rico": -14400,
        "America/Punta_Arenas": -10800,
        "America/Rankin_Inlet": -18000,
        "America/Recife": -10800,
        "America/Regina": -21600,
        "America/Resolute": -18000,
        "America/Rio_Branco": -18000,
        "America/Santarem": -10800,
        "America/Santiago": -14400,
        "America/Santo_Domingo": -14400,
        "America/Sao_Paulo": -10800,
        "America/Scoresbysund": -3600,
        "America/Sitka": -28800,
        "America/St_Barthelemy": -14400,
        "America/St_Johns": -9000,
        "America/St_Kitts": -14400,
        "America/St_Lucia": -14400,
        "America/St_Thomas": -14400,
        "America/St_Vincent": -14400,
        "America/Swift_Current": -21600,
        "America/Tegucigalpa": -21600,
        "America/Thule": -10800,
        "America/Tijuana": -25200,
        "America/Toronto": -14400,
        "America/Tortola": -14400,
        "America/Vancouver": -25200,
        "America/Whitehorse": -25200,
        "America/Winnipeg": -18000,
        "America/Yakutat": -28800,
        "Antarctica/Casey": 28800,
        "Antarctica/Davis": 25200,
        "Antarctica/DumontDUrville": 36000,
        "Antarctica/Macquarie": 36000,
        "Antarctica/Mawson": 18000,
        "Antarctica/McMurdo": 43200,
        "Antarctica/Palmer": -10800,
        "Antarctica/Rothera": -10800,
        "Antarctica/Syowa": 10800,
        "Antarctica/Troll": 7200,
        "Antarctica/Vostok": 18000,
        "Arctic/Longyearbyen": 7200,
        "Asia/Aden": 10800,
        "Asia/Almaty": 18000,
        "Asia/Amman": 10800,
        "Asia/Anadyr": 43200,
        "Asia/Aqtau": 18000,
        "Asia/Aqtobe": 18000,
        "Asia/Ashgabat": 18000,
        "Asia/Atyrau": 18000,
        "Asia/Baghdad": 10800,
        "Asia/Bahrain": 10800,
        "Asia/Baku": 14400,
        "Asia/Bangkok": 25200,
        "Asia/Barnaul": 25200,
        "Asia/Beirut": 10800,
        "Asia/Bishkek": 21600,
        "Asia/Brunei": 28800,
        "Asia/Chita": 32400,
        "Asia/Colombo": 19800,
        "Asia/Damascus": 10800,
        "Asia/Dhaka": 21600,
        "Asia/Dili": 32400,
        "Asia/Dubai": 14400,
        "Asia/Dushanbe": 18000,
        "Asia/Famagusta": 10800,
        "Asia/Gaza": 10800,
        "Asia/Hebron": 10800,
        "Asia/Ho_Chi_Minh": 25200,
        "Asia/Hong_Kong": 28800,
        "Asia/Hovd": 25200,
        "Asia/Irkutsk": 28800,
        "Asia/Jakarta": 25200,
        "Asia/Jayapura": 32400,
        "Asia/Jerusalem": 10800,
        "Asia/Kabul": 16200,
        "Asia/Kamchatka": 43200,
        "Asia/Karachi": 18000,
        "Asia/Kathmandu": 20700,
        "Asia/Khandyga": 32400,
        "Asia/Kolkata": 19800,
        "Asia/Krasnoyarsk": 25200,
        "Asia/Kuala_Lumpur": 28800,
        "Asia/Kuching": 28800,
        "Asia/Kuwait": 10800,
        "Asia/Macau": 28800,
        "Asia/Magadan": 39600,
        "Asia/Makassar": 28800,
        "Asia/Manila": 28800,
        "Asia/Muscat": 14400,
        "Asia/Nicosia": 10800,
        "Asia/Novokuznetsk": 25200,
        "Asia/Novosibirsk": 25200,
        "Asia/Omsk": 21600,
        "Asia/Oral": 18000,
        "Asia/Phnom_Penh": 25200,
        "Asia/Pontianak": 25200,
        "Asia/Pyongyang": 32400,
        "Asia/Qatar": 10800,
        "Asia/Qostanay": 18000,
        "Asia/Qyzylorda": 18000,
        "Asia/Riyadh": 10800,
        "Asia/Sakhalin": 39600,
        "Asia/Samarkand": 18000,
        "Asia/Seoul": 32400,
        "Asia/Shanghai": 28800,
        "Asia/Singapore": 28800,
        "Asia/Srednekolymsk": 39600,
        "Asia/Taipei": 28800,
        "Asia/Tashkent": 18000,
        "Asia/Tbilisi": 14400,
        "Asia/Tehran": 12600,
        "Asia/Thimphu": 21600,
        "Asia/Tokyo": 32400,
        "Asia/Tomsk": 25200,
        "Asia/Ulaanbaatar": 28800,
        "Asia/Urumqi": 21600,
        "Asia/Ust-Nera": 36000,
        "Asia/Vientiane": 25200,
        "Asia/Vladivostok": 36000,
        "Asia/Yakutsk": 32400,
        "Asia/Yangon": 23400,
        "Asia/Yekaterinburg": 18000,
        "Asia/Yerevan": 14400,
        "Atlantic/Azores": 0,
        "Atlantic/Bermuda": -10800,
        "Atlantic/Canary": 3600,
        "Atlantic/Cape_Verde": -3600,
        "Atlantic/Faroe": 3600,
        "Atlantic/Madeira": 3600,
        "Atlantic/Reykjavik": 0,
        "Atlantic/South_Georgia": -7200,
        "Atlantic/St_Helena": 0,
        "Atlantic/Stanley": -10800,
        "Australia/Adelaide": 34200,
        "Australia/Brisbane": 36000,
        "Australia/Broken_Hill": 34200,
        "Australia/Darwin": 34200,
        "Australia/Eucla": 31500,
        "Australia/Hobart": 36000,
        "Australia/Lindeman": 36000,
        "Australia/Lord_Howe": 37800,
        "Australia/Melbourne": 36000,
        "Australia/Perth": 28800,
        "Australia/Sydney": 36000,
        "Europe/Amsterdam": 7200,
        "Europe/Andorra": 7200,
        "Europe/Astrakhan": 14400,
        "Europe/Athens": 10800,
        "Europe/Belgrade": 7200,
        "Europe/Berlin": 7200,
        "Europe/Bratislava": 7200,
        "Europe/Brussels": 7200,
        "Europe/Bucharest": 10800,
        "Europe/Budapest": 7200,
        "Europe/Busingen": 7200,
        "Europe/Chisinau": 10800,
        "Europe/Copenhagen": 7200,
        "Europe/Dublin": 3600,
        "Europe/Gibraltar": 7200,
        "Europe/Guernsey": 3600,
        "Europe/Helsinki": 10800,
        "Europe/Isle_of_Man": 3600,
        "Europe/Istanbul": 10800,
        "Europe/Jersey": 3600,
        "Europe/Kaliningrad": 7200,
        "Europe/Kirov": 10800,
        "Europe/Kyiv": 10800,
        "Europe/Lisbon": 3600,
        "Europe/Ljubljana": 7200,
        "Europe/London": 3600,
        "Europe/Luxembourg": 7200,
        "Europe/Madrid": 7200,
        "Europe/Malta": 7200,
        "Europe/Mariehamn": 10800,
        "Europe/Minsk": 10800,
        "Europe/Monaco": 7200,
        "Europe/Moscow": 10800,
        "Europe/Oslo": 7200,
        "Europe/Paris": 7200,
        "Europe/Podgorica": 7200,
        "Europe/Prague": 7200,
        "Europe/Riga": 10800,
        "Europe/Rome": 7200,
        "Europe/Samara": 14400,
        "Europe/San_Marino": 7200,
        "Europe/Sarajevo": 7200,
        "Europe/Saratov": 14400,
        "Europe/Simferopol": 10800,
        "Europe/Skopje": 7200,
        "Europe/Sofia": 10800,
        "Europe/Stockholm": 7200,
        "Europe/Tallinn": 10800,
        "Europe/Tirane": 7200,
        "Europe/Ulyanovsk": 14400,
        "Europe/Vaduz": 7200,
        "Europe/Vatican": 7200,
        "Europe/Vienna": 7200,
        "Europe/Vilnius": 10800,
        "Europe/Volgograd": 10800,
        "Europe/Warsaw": 7200,
        "Europe/Zagreb": 7200,
        "Europe/Zurich": 7200,
        "Indian/Antananarivo": 10800,
        "Indian/Chagos": 21600,
        "Indian/Christmas": 25200,
        "Indian/Cocos": 23400,
        "Indian/Comoro": 10800,
        "Indian/Kerguelen": 18000,
        "Indian/Mahe": 14400,
        "Indian/Maldives": 18000,
        "Indian/Mauritius": 14400,
        "Indian/Mayotte": 10800,
        "Indian/Reunion": 14400,
        "Pacific/Apia": 46800,
        "Pacific/Auckland": 43200,
        "Pacific/Bougainville": 39600,
        "Pacific/Chatham": 45900,
        "Pacific/Chuuk": 36000,
        "Pacific/Easter": -21600,
        "Pacific/Efate": 39600,
        "Pacific/Fakaofo": 46800,
        "Pacific/Fiji": 43200,
        "Pacific/Funafuti": 43200,
        "Pacific/Galapagos": -21600,
        "Pacific/Gambier": -32400,
        "Pacific/Guadalcanal": 39600,
        "Pacific/Guam": 36000,
        "Pacific/Honolulu": -36000,
        "Pacific/Kanton": 46800,
        "Pacific/Kiritimati": 50400,
        "Pacific/Kosrae": 39600,
        "Pacific/Kwajalein": 43200,
        "Pacific/Majuro": 43200,
        "Pacific/Marquesas": -34200,
        "Pacific/Midway": -39600,
        "Pacific/Nauru": 43200,
        "Pacific/Niue": -39600,
        "Pacific/Norfolk": 39600,
        "Pacific/Noumea": 39600,
        "Pacific/Pago_Pago": -39600,
        "Pacific/Palau": 32400,
        "Pacific/Pitcairn": -28800,
        "Pacific/Pohnpei": 39600,
        "Pacific/Port_Moresby": 36000,
        "Pacific/Rarotonga": -36000,
        "Pacific/Saipan": 36000,
        "Pacific/Tahiti": -36000,
        "Pacific/Tarawa": 43200,
        "Pacific/Tongatapu": 46800,
        "Pacific/Wake": 43200,
        "Pacific/Wallis": 43200,
        "UTC": 0,
    ]

    @MainActor static public let TIME_ZONES_GROUPPED_LIST: [Int: GruppedListItem<String>] = [

        50400: GruppedListItem(
            title: "+14:00",
            items: [
                "Pacific/Kiritimati": NSLocalizedString("Pacific / Kiritimati", comment: ""),
            ]),

        46800: GruppedListItem(
            title: "+13:00",
            items: [
                "Pacific/Apia"     : NSLocalizedString("Pacific / Apia", comment: ""),
                "Pacific/Fakaofo"  : NSLocalizedString("Pacific / Fakaofo", comment: ""),
                "Pacific/Kanton"   : NSLocalizedString("Pacific / Kanton", comment: ""),
                "Pacific/Tongatapu": NSLocalizedString("Pacific / Tongatapu", comment: ""),
            ]),

        45900: GruppedListItem(
            title: "+12:45",
            items: [
                "Pacific/Chatham": NSLocalizedString("Pacific / Chatham", comment: ""),
            ]),

        43200: GruppedListItem(
            title: "+12:00",
            items: [
                "Antarctica/McMurdo": NSLocalizedString("Antarctica / McMurdo", comment: ""),
                "Asia/Anadyr"       : NSLocalizedString("Asia / Anadyr", comment: ""),
                "Asia/Kamchatka"    : NSLocalizedString("Asia / Kamchatka", comment: ""),
                "Pacific/Auckland"  : NSLocalizedString("Pacific / Auckland", comment: ""),
                "Pacific/Fiji"      : NSLocalizedString("Pacific / Fiji", comment: ""),
                "Pacific/Funafuti"  : NSLocalizedString("Pacific / Funafuti", comment: ""),
                "Pacific/Kwajalein" : NSLocalizedString("Pacific / Kwajalein", comment: ""),
                "Pacific/Majuro"    : NSLocalizedString("Pacific / Majuro", comment: ""),
                "Pacific/Nauru"     : NSLocalizedString("Pacific / Nauru", comment: ""),
                "Pacific/Tarawa"    : NSLocalizedString("Pacific / Tarawa", comment: ""),
                "Pacific/Wake"      : NSLocalizedString("Pacific / Wake", comment: ""),
                "Pacific/Wallis"    : NSLocalizedString("Pacific / Wallis", comment: ""),
            ]),

        39600: GruppedListItem(
            title: "+11:00",
            items: [
                "Asia/Magadan"        : NSLocalizedString("Asia / Magadan", comment: ""),
                "Asia/Sakhalin"       : NSLocalizedString("Asia / Sakhalin", comment: ""),
                "Asia/Srednekolymsk"  : NSLocalizedString("Asia / Srednekolymsk", comment: ""),
                "Pacific/Bougainville": NSLocalizedString("Pacific / Bougainville", comment: ""),
                "Pacific/Efate"       : NSLocalizedString("Pacific / Efate", comment: ""),
                "Pacific/Guadalcanal" : NSLocalizedString("Pacific / Guadalcanal", comment: ""),
                "Pacific/Kosrae"      : NSLocalizedString("Pacific / Kosrae", comment: ""),
                "Pacific/Norfolk"     : NSLocalizedString("Pacific / Norfolk", comment: ""),
                "Pacific/Noumea"      : NSLocalizedString("Pacific / Noumea", comment: ""),
                "Pacific/Pohnpei"     : NSLocalizedString("Pacific / Pohnpei", comment: ""),
            ]),

        37800: GruppedListItem(
            title: "+10:30",
            items: [
                "Australia/Lord_Howe": NSLocalizedString("Australia / Lord-Howe", comment: ""),
            ]),

        36000: GruppedListItem(
            title: "+10:00",
            items: [
                "Antarctica/DumontDUrville": NSLocalizedString("Antarctica / DumontDUrville", comment: ""),
                "Antarctica/Macquarie"     : NSLocalizedString("Antarctica / Macquarie", comment: ""),
                "Asia/Ust-Nera"            : NSLocalizedString("Asia / Ust-Nera", comment: ""),
                "Asia/Vladivostok"         : NSLocalizedString("Asia / Vladivostok", comment: ""),
                "Australia/Brisbane"       : NSLocalizedString("Australia / Brisbane", comment: ""),
                "Australia/Hobart"         : NSLocalizedString("Australia / Hobart", comment: ""),
                "Australia/Lindeman"       : NSLocalizedString("Australia / Lindeman", comment: ""),
                "Australia/Melbourne"      : NSLocalizedString("Australia / Melbourne", comment: ""),
                "Australia/Sydney"         : NSLocalizedString("Australia / Sydney", comment: ""),
                "Pacific/Chuuk"            : NSLocalizedString("Pacific / Chuuk", comment: ""),
                "Pacific/Guam"             : NSLocalizedString("Pacific / Guam", comment: ""),
                "Pacific/Port_Moresby"     : NSLocalizedString("Pacific / Port-Moresby", comment: ""),
                "Pacific/Saipan"           : NSLocalizedString("Pacific / Saipan", comment: ""),
            ]),

        34200: GruppedListItem(
            title: "+09:30",
            items: [
                "Australia/Adelaide"   : NSLocalizedString("Australia / Adelaide", comment: ""),
                "Australia/Broken_Hill": NSLocalizedString("Australia / Broken-Hill", comment: ""),
                "Australia/Darwin"     : NSLocalizedString("Australia / Darwin", comment: ""),
            ]),

        32400: GruppedListItem(
            title: "+09:00",
            items: [
                "Asia/Chita"    : NSLocalizedString("Asia / Chita", comment: ""),
                "Asia/Dili"     : NSLocalizedString("Asia / Dili", comment: ""),
                "Asia/Jayapura" : NSLocalizedString("Asia / Jayapura", comment: ""),
                "Asia/Khandyga" : NSLocalizedString("Asia / Khandyga", comment: ""),
                "Asia/Pyongyang": NSLocalizedString("Asia / Pyongyang", comment: ""),
                "Asia/Seoul"    : NSLocalizedString("Asia / Seoul", comment: ""),
                "Asia/Tokyo"    : NSLocalizedString("Asia / Tokyo", comment: ""),
                "Asia/Yakutsk"  : NSLocalizedString("Asia / Yakutsk", comment: ""),
                "Pacific/Palau" : NSLocalizedString("Pacific / Palau", comment: ""),
            ]),

        31500: GruppedListItem(
            title: "+08:45",
            items: [
                "Australia/Eucla": NSLocalizedString("Australia / Eucla", comment: ""),
            ]),

        28800: GruppedListItem(
            title: "+08:00",
            items: [
                "Antarctica/Casey" : NSLocalizedString("Antarctica / Casey", comment: ""),
                "Asia/Brunei"      : NSLocalizedString("Asia / Brunei", comment: ""),
                "Asia/Hong_Kong"   : NSLocalizedString("Asia / Hong-Kong", comment: ""),
                "Asia/Irkutsk"     : NSLocalizedString("Asia / Irkutsk", comment: ""),
                "Asia/Kuala_Lumpur": NSLocalizedString("Asia / Kuala-Lumpur", comment: ""),
                "Asia/Kuching"     : NSLocalizedString("Asia / Kuching", comment: ""),
                "Asia/Macau"       : NSLocalizedString("Asia / Macau", comment: ""),
                "Asia/Makassar"    : NSLocalizedString("Asia / Makassar", comment: ""),
                "Asia/Manila"      : NSLocalizedString("Asia / Manila", comment: ""),
                "Asia/Shanghai"    : NSLocalizedString("Asia / Shanghai", comment: ""),
                "Asia/Singapore"   : NSLocalizedString("Asia / Singapore", comment: ""),
                "Asia/Taipei"      : NSLocalizedString("Asia / Taipei", comment: ""),
                "Asia/Ulaanbaatar" : NSLocalizedString("Asia / Ulaanbaatar", comment: ""),
                "Australia/Perth"  : NSLocalizedString("Australia / Perth", comment: ""),
            ]),

        25200: GruppedListItem(
            title: "+07:00",
            items: [
                "Antarctica/Davis" : NSLocalizedString("Antarctica / Davis", comment: ""),
                "Asia/Bangkok"     : NSLocalizedString("Asia / Bangkok", comment: ""),
                "Asia/Barnaul"     : NSLocalizedString("Asia / Barnaul", comment: ""),
                "Asia/Ho_Chi_Minh" : NSLocalizedString("Asia / Ho-Chi-Minh", comment: ""),
                "Asia/Hovd"        : NSLocalizedString("Asia / Hovd", comment: ""),
                "Asia/Jakarta"     : NSLocalizedString("Asia / Jakarta", comment: ""),
                "Asia/Krasnoyarsk" : NSLocalizedString("Asia / Krasnoyarsk", comment: ""),
                "Asia/Novokuznetsk": NSLocalizedString("Asia / Novokuznetsk", comment: ""),
                "Asia/Novosibirsk" : NSLocalizedString("Asia / Novosibirsk", comment: ""),
                "Asia/Phnom_Penh"  : NSLocalizedString("Asia / Phnom-Penh", comment: ""),
                "Asia/Pontianak"   : NSLocalizedString("Asia / Pontianak", comment: ""),
                "Asia/Tomsk"       : NSLocalizedString("Asia / Tomsk", comment: ""),
                "Asia/Vientiane"   : NSLocalizedString("Asia / Vientiane", comment: ""),
                "Indian/Christmas" : NSLocalizedString("Indian / Christmas", comment: ""),
            ]),

        23400: GruppedListItem(
            title: "+06:30",
            items: [
                "Asia/Yangon" : NSLocalizedString("Asia / Yangon", comment: ""),
                "Indian/Cocos": NSLocalizedString("Indian / Cocos", comment: ""),
            ]),

        21600: GruppedListItem(
            title: "+06:00",
            items: [
                "Asia/Bishkek" : NSLocalizedString("Asia / Bishkek", comment: ""),
                "Asia/Dhaka"   : NSLocalizedString("Asia / Dhaka", comment: ""),
                "Asia/Omsk"    : NSLocalizedString("Asia / Omsk", comment: ""),
                "Asia/Thimphu" : NSLocalizedString("Asia / Thimphu", comment: ""),
                "Asia/Urumqi"  : NSLocalizedString("Asia / Urumqi", comment: ""),
                "Indian/Chagos": NSLocalizedString("Indian / Chagos", comment: ""),
            ]),

        20700: GruppedListItem(
            title: "+05:45",
            items: [
                "Asia/Kathmandu": NSLocalizedString("Asia / Kathmandu", comment: ""),
            ]),

        19800: GruppedListItem(
            title: "+05:30",
            items: [
                "Asia/Colombo": NSLocalizedString("Asia / Colombo", comment: ""),
                "Asia/Kolkata": NSLocalizedString("Asia / Kolkata", comment: ""),
            ]),

        18000: GruppedListItem(
            title: "+05:00",
            items: [
                "Antarctica/Mawson" : NSLocalizedString("Antarctica / Mawson", comment: ""),
                "Antarctica/Vostok" : NSLocalizedString("Antarctica / Vostok", comment: ""),
                "Asia/Almaty"       : NSLocalizedString("Asia / Almaty", comment: ""),
                "Asia/Aqtau"        : NSLocalizedString("Asia / Aqtau", comment: ""),
                "Asia/Aqtobe"       : NSLocalizedString("Asia / Aqtobe", comment: ""),
                "Asia/Ashgabat"     : NSLocalizedString("Asia / Ashgabat", comment: ""),
                "Asia/Atyrau"       : NSLocalizedString("Asia / Atyrau", comment: ""),
                "Asia/Dushanbe"     : NSLocalizedString("Asia / Dushanbe", comment: ""),
                "Asia/Karachi"      : NSLocalizedString("Asia / Karachi", comment: ""),
                "Asia/Oral"         : NSLocalizedString("Asia / Oral", comment: ""),
                "Asia/Qostanay"     : NSLocalizedString("Asia / Qostanay", comment: ""),
                "Asia/Qyzylorda"    : NSLocalizedString("Asia / Qyzylorda", comment: ""),
                "Asia/Samarkand"    : NSLocalizedString("Asia / Samarkand", comment: ""),
                "Asia/Tashkent"     : NSLocalizedString("Asia / Tashkent", comment: ""),
                "Asia/Yekaterinburg": NSLocalizedString("Asia / Yekaterinburg", comment: ""),
                "Indian/Kerguelen"  : NSLocalizedString("Indian / Kerguelen", comment: ""),
                "Indian/Maldives"   : NSLocalizedString("Indian / Maldives", comment: ""),
            ]),

        16200: GruppedListItem(
            title: "+04:30",
            items: [
                "Asia/Kabul": NSLocalizedString("Asia / Kabul", comment: ""),
            ]),

        14400: GruppedListItem(
            title: "+04:00",
            items: [
                "Asia/Baku"       : NSLocalizedString("Asia / Baku", comment: ""),
                "Asia/Dubai"      : NSLocalizedString("Asia / Dubai", comment: ""),
                "Asia/Muscat"     : NSLocalizedString("Asia / Muscat", comment: ""),
                "Asia/Tbilisi"    : NSLocalizedString("Asia / Tbilisi", comment: ""),
                "Asia/Yerevan"    : NSLocalizedString("Asia / Yerevan", comment: ""),
                "Europe/Astrakhan": NSLocalizedString("Europe / Astrakhan", comment: ""),
                "Europe/Samara"   : NSLocalizedString("Europe / Samara", comment: ""),
                "Europe/Saratov"  : NSLocalizedString("Europe / Saratov", comment: ""),
                "Europe/Ulyanovsk": NSLocalizedString("Europe / Ulyanovsk", comment: ""),
                "Indian/Mahe"     : NSLocalizedString("Indian / Mahe", comment: ""),
                "Indian/Mauritius": NSLocalizedString("Indian / Mauritius", comment: ""),
                "Indian/Reunion"  : NSLocalizedString("Indian / Reunion", comment: ""),
            ]),

        12600: GruppedListItem(
            title: "+03:30",
            items: [
                "Asia/Tehran": NSLocalizedString("Asia / Tehran", comment: ""),
            ]),

        10800: GruppedListItem(
            title: "+03:00",
            items: [
                "Africa/Addis_Ababa"  : NSLocalizedString("Africa / Addis-Ababa", comment: ""),
                "Africa/Asmara"       : NSLocalizedString("Africa / Asmara", comment: ""),
                "Africa/Cairo"        : NSLocalizedString("Africa / Cairo", comment: ""),
                "Africa/Dar_es_Salaam": NSLocalizedString("Africa / Dar-es-Salaam", comment: ""),
                "Africa/Djibouti"     : NSLocalizedString("Africa / Djibouti", comment: ""),
                "Africa/Kampala"      : NSLocalizedString("Africa / Kampala", comment: ""),
                "Africa/Mogadishu"    : NSLocalizedString("Africa / Mogadishu", comment: ""),
                "Africa/Nairobi"      : NSLocalizedString("Africa / Nairobi", comment: ""),
                "Antarctica/Syowa"    : NSLocalizedString("Antarctica / Syowa", comment: ""),
                "Asia/Aden"           : NSLocalizedString("Asia / Aden", comment: ""),
                "Asia/Amman"          : NSLocalizedString("Asia / Amman", comment: ""),
                "Asia/Baghdad"        : NSLocalizedString("Asia / Baghdad", comment: ""),
                "Asia/Bahrain"        : NSLocalizedString("Asia / Bahrain", comment: ""),
                "Asia/Beirut"         : NSLocalizedString("Asia / Beirut", comment: ""),
                "Asia/Damascus"       : NSLocalizedString("Asia / Damascus", comment: ""),
                "Asia/Famagusta"      : NSLocalizedString("Asia / Famagusta", comment: ""),
                "Asia/Gaza"           : NSLocalizedString("Asia / Gaza", comment: ""),
                "Asia/Hebron"         : NSLocalizedString("Asia / Hebron", comment: ""),
                "Asia/Jerusalem"      : NSLocalizedString("Asia / Jerusalem", comment: ""),
                "Asia/Kuwait"         : NSLocalizedString("Asia / Kuwait", comment: ""),
                "Asia/Nicosia"        : NSLocalizedString("Asia / Nicosia", comment: ""),
                "Asia/Qatar"          : NSLocalizedString("Asia / Qatar", comment: ""),
                "Asia/Riyadh"         : NSLocalizedString("Asia / Riyadh", comment: ""),
                "Europe/Athens"       : NSLocalizedString("Europe / Athens", comment: ""),
                "Europe/Bucharest"    : NSLocalizedString("Europe / Bucharest", comment: ""),
                "Europe/Chisinau"     : NSLocalizedString("Europe / Chisinau", comment: ""),
                "Europe/Helsinki"     : NSLocalizedString("Europe / Helsinki", comment: ""),
                "Europe/Istanbul"     : NSLocalizedString("Europe / Istanbul", comment: ""),
                "Europe/Kirov"        : NSLocalizedString("Europe / Kirov", comment: ""),
                "Europe/Kyiv"         : NSLocalizedString("Europe / Kyiv", comment: ""),
                "Europe/Mariehamn"    : NSLocalizedString("Europe / Mariehamn", comment: ""),
                "Europe/Minsk"        : NSLocalizedString("Europe / Minsk", comment: ""),
                "Europe/Moscow"       : NSLocalizedString("Europe / Moscow", comment: ""),
                "Europe/Riga"         : NSLocalizedString("Europe / Riga", comment: ""),
                "Europe/Simferopol"   : NSLocalizedString("Europe / Simferopol", comment: ""),
                "Europe/Sofia"        : NSLocalizedString("Europe / Sofia", comment: ""),
                "Europe/Tallinn"      : NSLocalizedString("Europe / Tallinn", comment: ""),
                "Europe/Vilnius"      : NSLocalizedString("Europe / Vilnius", comment: ""),
                "Europe/Volgograd"    : NSLocalizedString("Europe / Volgograd", comment: ""),
                "Indian/Antananarivo" : NSLocalizedString("Indian / Antananarivo", comment: ""),
                "Indian/Comoro"       : NSLocalizedString("Indian / Comoro", comment: ""),
                "Indian/Mayotte"      : NSLocalizedString("Indian / Mayotte", comment: ""),
            ]),

        7200: GruppedListItem(
            title: "+02:00",
            items: [
                "Africa/Blantyre"    : NSLocalizedString("Africa / Blantyre", comment: ""),
                "Africa/Bujumbura"   : NSLocalizedString("Africa / Bujumbura", comment: ""),
                "Africa/Ceuta"       : NSLocalizedString("Africa / Ceuta", comment: ""),
                "Africa/Gaborone"    : NSLocalizedString("Africa / Gaborone", comment: ""),
                "Africa/Harare"      : NSLocalizedString("Africa / Harare", comment: ""),
                "Africa/Johannesburg": NSLocalizedString("Africa / Johannesburg", comment: ""),
                "Africa/Juba"        : NSLocalizedString("Africa / Juba", comment: ""),
                "Africa/Khartoum"    : NSLocalizedString("Africa / Khartoum", comment: ""),
                "Africa/Kigali"      : NSLocalizedString("Africa / Kigali", comment: ""),
                "Africa/Lubumbashi"  : NSLocalizedString("Africa / Lubumbashi", comment: ""),
                "Africa/Lusaka"      : NSLocalizedString("Africa / Lusaka", comment: ""),
                "Africa/Maputo"      : NSLocalizedString("Africa / Maputo", comment: ""),
                "Africa/Maseru"      : NSLocalizedString("Africa / Maseru", comment: ""),
                "Africa/Mbabane"     : NSLocalizedString("Africa / Mbabane", comment: ""),
                "Africa/Tripoli"     : NSLocalizedString("Africa / Tripoli", comment: ""),
                "Africa/Windhoek"    : NSLocalizedString("Africa / Windhoek", comment: ""),
                "Antarctica/Troll"   : NSLocalizedString("Antarctica / Troll", comment: ""),
                "Arctic/Longyearbyen": NSLocalizedString("Arctic / Longyearbyen", comment: ""),
                "Europe/Amsterdam"   : NSLocalizedString("Europe / Amsterdam", comment: ""),
                "Europe/Andorra"     : NSLocalizedString("Europe / Andorra", comment: ""),
                "Europe/Belgrade"    : NSLocalizedString("Europe / Belgrade", comment: ""),
                "Europe/Berlin"      : NSLocalizedString("Europe / Berlin", comment: ""),
                "Europe/Bratislava"  : NSLocalizedString("Europe / Bratislava", comment: ""),
                "Europe/Brussels"    : NSLocalizedString("Europe / Brussels", comment: ""),
                "Europe/Budapest"    : NSLocalizedString("Europe / Budapest", comment: ""),
                "Europe/Busingen"    : NSLocalizedString("Europe / Busingen", comment: ""),
                "Europe/Copenhagen"  : NSLocalizedString("Europe / Copenhagen", comment: ""),
                "Europe/Gibraltar"   : NSLocalizedString("Europe / Gibraltar", comment: ""),
                "Europe/Kaliningrad" : NSLocalizedString("Europe / Kaliningrad", comment: ""),
                "Europe/Ljubljana"   : NSLocalizedString("Europe / Ljubljana", comment: ""),
                "Europe/Luxembourg"  : NSLocalizedString("Europe / Luxembourg", comment: ""),
                "Europe/Madrid"      : NSLocalizedString("Europe / Madrid", comment: ""),
                "Europe/Malta"       : NSLocalizedString("Europe / Malta", comment: ""),
                "Europe/Monaco"      : NSLocalizedString("Europe / Monaco", comment: ""),
                "Europe/Oslo"        : NSLocalizedString("Europe / Oslo", comment: ""),
                "Europe/Paris"       : NSLocalizedString("Europe / Paris", comment: ""),
                "Europe/Podgorica"   : NSLocalizedString("Europe / Podgorica", comment: ""),
                "Europe/Prague"      : NSLocalizedString("Europe / Prague", comment: ""),
                "Europe/Rome"        : NSLocalizedString("Europe / Rome", comment: ""),
                "Europe/San_Marino"  : NSLocalizedString("Europe / San-Marino", comment: ""),
                "Europe/Sarajevo"    : NSLocalizedString("Europe / Sarajevo", comment: ""),
                "Europe/Skopje"      : NSLocalizedString("Europe / Skopje", comment: ""),
                "Europe/Stockholm"   : NSLocalizedString("Europe / Stockholm", comment: ""),
                "Europe/Tirane"      : NSLocalizedString("Europe / Tirane", comment: ""),
                "Europe/Vaduz"       : NSLocalizedString("Europe / Vaduz", comment: ""),
                "Europe/Vatican"     : NSLocalizedString("Europe / Vatican", comment: ""),
                "Europe/Vienna"      : NSLocalizedString("Europe / Vienna", comment: ""),
                "Europe/Warsaw"      : NSLocalizedString("Europe / Warsaw", comment: ""),
                "Europe/Zagreb"      : NSLocalizedString("Europe / Zagreb", comment: ""),
                "Europe/Zurich"      : NSLocalizedString("Europe / Zurich", comment: ""),
            ]),

        3600: GruppedListItem(
            title: "+01:00",
            items: [
                "Africa/Algiers"    : NSLocalizedString("Africa / Algiers", comment: ""),
                "Africa/Bangui"     : NSLocalizedString("Africa / Bangui", comment: ""),
                "Africa/Brazzaville": NSLocalizedString("Africa / Brazzaville", comment: ""),
                "Africa/Casablanca" : NSLocalizedString("Africa / Casablanca", comment: ""),
                "Africa/Douala"     : NSLocalizedString("Africa / Douala", comment: ""),
                "Africa/El_Aaiun"   : NSLocalizedString("Africa / El-Aaiun", comment: ""),
                "Africa/Kinshasa"   : NSLocalizedString("Africa / Kinshasa", comment: ""),
                "Africa/Lagos"      : NSLocalizedString("Africa / Lagos", comment: ""),
                "Africa/Libreville" : NSLocalizedString("Africa / Libreville", comment: ""),
                "Africa/Luanda"     : NSLocalizedString("Africa / Luanda", comment: ""),
                "Africa/Malabo"     : NSLocalizedString("Africa / Malabo", comment: ""),
                "Africa/Ndjamena"   : NSLocalizedString("Africa / Ndjamena", comment: ""),
                "Africa/Niamey"     : NSLocalizedString("Africa / Niamey", comment: ""),
                "Africa/Porto-Novo" : NSLocalizedString("Africa / Porto-Novo", comment: ""),
                "Africa/Tunis"      : NSLocalizedString("Africa / Tunis", comment: ""),
                "Atlantic/Canary"   : NSLocalizedString("Atlantic / Canary", comment: ""),
                "Atlantic/Faroe"    : NSLocalizedString("Atlantic / Faroe", comment: ""),
                "Atlantic/Madeira"  : NSLocalizedString("Atlantic / Madeira", comment: ""),
                "Europe/Dublin"     : NSLocalizedString("Europe / Dublin", comment: ""),
                "Europe/Guernsey"   : NSLocalizedString("Europe / Guernsey", comment: ""),
                "Europe/Isle_of_Man": NSLocalizedString("Europe / Isle-of-Man", comment: ""),
                "Europe/Jersey"     : NSLocalizedString("Europe / Jersey", comment: ""),
                "Europe/Lisbon"     : NSLocalizedString("Europe / Lisbon", comment: ""),
                "Europe/London"     : NSLocalizedString("Europe / London", comment: ""),
            ]),

        0: GruppedListItem(
            title: "+00:00",
            items: [
                "Africa/Abidjan"      : NSLocalizedString("Africa / Abidjan", comment: ""),
                "Africa/Accra"        : NSLocalizedString("Africa / Accra", comment: ""),
                "Africa/Bamako"       : NSLocalizedString("Africa / Bamako", comment: ""),
                "Africa/Banjul"       : NSLocalizedString("Africa / Banjul", comment: ""),
                "Africa/Bissau"       : NSLocalizedString("Africa / Bissau", comment: ""),
                "Africa/Conakry"      : NSLocalizedString("Africa / Conakry", comment: ""),
                "Africa/Dakar"        : NSLocalizedString("Africa / Dakar", comment: ""),
                "Africa/Freetown"     : NSLocalizedString("Africa / Freetown", comment: ""),
                "Africa/Lome"         : NSLocalizedString("Africa / Lome", comment: ""),
                "Africa/Monrovia"     : NSLocalizedString("Africa / Monrovia", comment: ""),
                "Africa/Nouakchott"   : NSLocalizedString("Africa / Nouakchott", comment: ""),
                "Africa/Ouagadougou"  : NSLocalizedString("Africa / Ouagadougou", comment: ""),
                "Africa/Sao_Tome"     : NSLocalizedString("Africa / Sao-Tome", comment: ""),
                "America/Danmarkshavn": NSLocalizedString("America / Danmarkshavn", comment: ""),
                "Atlantic/Azores"     : NSLocalizedString("Atlantic / Azores", comment: ""),
                "Atlantic/Reykjavik"  : NSLocalizedString("Atlantic / Reykjavik", comment: ""),
                "Atlantic/St_Helena"  : NSLocalizedString("Atlantic / St-Helena", comment: ""),
                "UTC"                 : NSLocalizedString("UTC", comment: ""),
            ]),

        -3600: GruppedListItem(
            title: "−01:00",
            items: [
                "America/Nuuk"        : NSLocalizedString("America / Nuuk", comment: ""),
                "America/Scoresbysund": NSLocalizedString("America / Scoresbysund", comment: ""),
                "Atlantic/Cape_Verde" : NSLocalizedString("Atlantic / Cape-Verde", comment: ""),
            ]),

        -7200: GruppedListItem(
            title: "−02:00",
            items: [
                "America/Miquelon"      : NSLocalizedString("America / Miquelon", comment: ""),
                "America/Noronha"       : NSLocalizedString("America / Noronha", comment: ""),
                "Atlantic/South_Georgia": NSLocalizedString("Atlantic / South-Georgia", comment: ""),
            ]),

        -9000: GruppedListItem(
            title: "−02:30",
            items: [
                "America/St_Johns": NSLocalizedString("America / St-Johns", comment: ""),
            ]),

        -10800: GruppedListItem(
            title: "−03:00",
            items: [
                "America/Araguaina"             : NSLocalizedString("America / Araguaina", comment: ""),
                "America/Argentina/Buenos_Aires": NSLocalizedString("America / Argentina / Buenos-Aires", comment: ""),
                "America/Argentina/Catamarca"   : NSLocalizedString("America / Argentina / Catamarca", comment: ""),
                "America/Argentina/Cordoba"     : NSLocalizedString("America / Argentina / Cordoba", comment: ""),
                "America/Argentina/Jujuy"       : NSLocalizedString("America / Argentina / Jujuy", comment: ""),
                "America/Argentina/La_Rioja"    : NSLocalizedString("America / Argentina / La-Rioja", comment: ""),
                "America/Argentina/Mendoza"     : NSLocalizedString("America / Argentina / Mendoza", comment: ""),
                "America/Argentina/Rio_Gallegos": NSLocalizedString("America / Argentina / Rio-Gallegos", comment: ""),
                "America/Argentina/Salta"       : NSLocalizedString("America / Argentina / Salta", comment: ""),
                "America/Argentina/San_Juan"    : NSLocalizedString("America / Argentina / San-Juan", comment: ""),
                "America/Argentina/San_Luis"    : NSLocalizedString("America / Argentina / San-Luis", comment: ""),
                "America/Argentina/Tucuman"     : NSLocalizedString("America / Argentina / Tucuman", comment: ""),
                "America/Argentina/Ushuaia"     : NSLocalizedString("America / Argentina / Ushuaia", comment: ""),
                "America/Asuncion"              : NSLocalizedString("America / Asuncion", comment: ""),
                "America/Bahia"                 : NSLocalizedString("America / Bahia", comment: ""),
                "America/Belem"                 : NSLocalizedString("America / Belem", comment: ""),
                "America/Cayenne"               : NSLocalizedString("America / Cayenne", comment: ""),
                "America/Coyhaique"             : NSLocalizedString("America / Coyhaique", comment: ""),
                "America/Fortaleza"             : NSLocalizedString("America / Fortaleza", comment: ""),
                "America/Glace_Bay"             : NSLocalizedString("America / Glace-Bay", comment: ""),
                "America/Goose_Bay"             : NSLocalizedString("America / Goose-Bay", comment: ""),
                "America/Halifax"               : NSLocalizedString("America / Halifax", comment: ""),
                "America/Maceio"                : NSLocalizedString("America / Maceio", comment: ""),
                "America/Moncton"               : NSLocalizedString("America / Moncton", comment: ""),
                "America/Montevideo"            : NSLocalizedString("America / Montevideo", comment: ""),
                "America/Paramaribo"            : NSLocalizedString("America / Paramaribo", comment: ""),
                "America/Punta_Arenas"          : NSLocalizedString("America / Punta-Arenas", comment: ""),
                "America/Recife"                : NSLocalizedString("America / Recife", comment: ""),
                "America/Santarem"              : NSLocalizedString("America / Santarem", comment: ""),
                "America/Sao_Paulo"             : NSLocalizedString("America / Sao-Paulo", comment: ""),
                "America/Thule"                 : NSLocalizedString("America / Thule", comment: ""),
                "Antarctica/Palmer"             : NSLocalizedString("Antarctica / Palmer", comment: ""),
                "Antarctica/Rothera"            : NSLocalizedString("Antarctica / Rothera", comment: ""),
                "Atlantic/Bermuda"              : NSLocalizedString("Atlantic / Bermuda", comment: ""),
                "Atlantic/Stanley"              : NSLocalizedString("Atlantic / Stanley", comment: ""),
            ]),

        -14400: GruppedListItem(
            title: "−04:00",
            items: [
                "America/Anguilla"            : NSLocalizedString("America / Anguilla", comment: ""),
                "America/Antigua"             : NSLocalizedString("America / Antigua", comment: ""),
                "America/Aruba"               : NSLocalizedString("America / Aruba", comment: ""),
                "America/Barbados"            : NSLocalizedString("America / Barbados", comment: ""),
                "America/Blanc-Sablon"        : NSLocalizedString("America / Blanc-Sablon", comment: ""),
                "America/Boa_Vista"           : NSLocalizedString("America / Boa-Vista", comment: ""),
                "America/Campo_Grande"        : NSLocalizedString("America / Campo-Grande", comment: ""),
                "America/Caracas"             : NSLocalizedString("America / Caracas", comment: ""),
                "America/Cuiaba"              : NSLocalizedString("America / Cuiaba", comment: ""),
                "America/Curacao"             : NSLocalizedString("America / Curacao", comment: ""),
                "America/Detroit"             : NSLocalizedString("America / Detroit", comment: ""),
                "America/Dominica"            : NSLocalizedString("America / Dominica", comment: ""),
                "America/Grand_Turk"          : NSLocalizedString("America / Grand-Turk", comment: ""),
                "America/Grenada"             : NSLocalizedString("America / Grenada", comment: ""),
                "America/Guadeloupe"          : NSLocalizedString("America / Guadeloupe", comment: ""),
                "America/Guyana"              : NSLocalizedString("America / Guyana", comment: ""),
                "America/Havana"              : NSLocalizedString("America / Havana", comment: ""),
                "America/Indiana/Indianapolis": NSLocalizedString("America / Indiana / Indianapolis", comment: ""),
                "America/Indiana/Marengo"     : NSLocalizedString("America / Indiana / Marengo", comment: ""),
                "America/Indiana/Petersburg"  : NSLocalizedString("America / Indiana / Petersburg", comment: ""),
                "America/Indiana/Vevay"       : NSLocalizedString("America / Indiana / Vevay", comment: ""),
                "America/Indiana/Vincennes"   : NSLocalizedString("America / Indiana / Vincennes", comment: ""),
                "America/Indiana/Winamac"     : NSLocalizedString("America / Indiana / Winamac", comment: ""),
                "America/Iqaluit"             : NSLocalizedString("America / Iqaluit", comment: ""),
                "America/Kentucky/Louisville" : NSLocalizedString("America / Kentucky / Louisville", comment: ""),
                "America/Kentucky/Monticello" : NSLocalizedString("America / Kentucky / Monticello", comment: ""),
                "America/Kralendijk"          : NSLocalizedString("America / Kralendijk", comment: ""),
                "America/La_Paz"              : NSLocalizedString("America / La-Paz", comment: ""),
                "America/Lower_Princes"       : NSLocalizedString("America / Lower-Princes", comment: ""),
                "America/Manaus"              : NSLocalizedString("America / Manaus", comment: ""),
                "America/Marigot"             : NSLocalizedString("America / Marigot", comment: ""),
                "America/Martinique"          : NSLocalizedString("America / Martinique", comment: ""),
                "America/Montserrat"          : NSLocalizedString("America / Montserrat", comment: ""),
                "America/Nassau"              : NSLocalizedString("America / Nassau", comment: ""),
                "America/New_York"            : NSLocalizedString("America / New-York", comment: ""),
                "America/Port-au-Prince"      : NSLocalizedString("America / Port-au-Prince", comment: ""),
                "America/Port_of_Spain"       : NSLocalizedString("America / Port-of-Spain", comment: ""),
                "America/Porto_Velho"         : NSLocalizedString("America / Porto-Velho", comment: ""),
                "America/Puerto_Rico"         : NSLocalizedString("America / Puerto-Rico", comment: ""),
                "America/Santiago"            : NSLocalizedString("America / Santiago", comment: ""),
                "America/Santo_Domingo"       : NSLocalizedString("America / Santo-Domingo", comment: ""),
                "America/St_Barthelemy"       : NSLocalizedString("America / St-Barthelemy", comment: ""),
                "America/St_Kitts"            : NSLocalizedString("America / St-Kitts", comment: ""),
                "America/St_Lucia"            : NSLocalizedString("America / St-Lucia", comment: ""),
                "America/St_Thomas"           : NSLocalizedString("America / St-Thomas", comment: ""),
                "America/St_Vincent"          : NSLocalizedString("America / St-Vincent", comment: ""),
                "America/Toronto"             : NSLocalizedString("America / Toronto", comment: ""),
                "America/Tortola"             : NSLocalizedString("America / Tortola", comment: ""),
            ]),

        -18000: GruppedListItem(
            title: "−05:00",
            items: [
                "America/Atikokan"              : NSLocalizedString("America / Atikokan", comment: ""),
                "America/Bogota"                : NSLocalizedString("America / Bogota", comment: ""),
                "America/Cancun"                : NSLocalizedString("America / Cancun", comment: ""),
                "America/Cayman"                : NSLocalizedString("America / Cayman", comment: ""),
                "America/Chicago"               : NSLocalizedString("America / Chicago", comment: ""),
                "America/Eirunepe"              : NSLocalizedString("America / Eirunepe", comment: ""),
                "America/Guayaquil"             : NSLocalizedString("America / Guayaquil", comment: ""),
                "America/Indiana/Knox"          : NSLocalizedString("America / Indiana / Knox", comment: ""),
                "America/Indiana/Tell_City"     : NSLocalizedString("America / Indiana / Tell-City", comment: ""),
                "America/Jamaica"               : NSLocalizedString("America / Jamaica", comment: ""),
                "America/Lima"                  : NSLocalizedString("America / Lima", comment: ""),
                "America/Matamoros"             : NSLocalizedString("America / Matamoros", comment: ""),
                "America/Menominee"             : NSLocalizedString("America / Menominee", comment: ""),
                "America/North_Dakota/Beulah"   : NSLocalizedString("America / North-Dakota / Beulah", comment: ""),
                "America/North_Dakota/Center"   : NSLocalizedString("America / North-Dakota / Center", comment: ""),
                "America/North_Dakota/New_Salem": NSLocalizedString("America / North-Dakota / New-Salem", comment: ""),
                "America/Ojinaga"               : NSLocalizedString("America / Ojinaga", comment: ""),
                "America/Panama"                : NSLocalizedString("America / Panama", comment: ""),
                "America/Rankin_Inlet"          : NSLocalizedString("America / Rankin-Inlet", comment: ""),
                "America/Resolute"              : NSLocalizedString("America / Resolute", comment: ""),
                "America/Rio_Branco"            : NSLocalizedString("America / Rio-Branco", comment: ""),
                "America/Winnipeg"              : NSLocalizedString("America / Winnipeg", comment: ""),
            ]),

        -21600: GruppedListItem(
            title: "−06:00",
            items: [
                "America/Bahia_Banderas": NSLocalizedString("America / Bahia-Banderas", comment: ""),
                "America/Belize"        : NSLocalizedString("America / Belize", comment: ""),
                "America/Boise"         : NSLocalizedString("America / Boise", comment: ""),
                "America/Cambridge_Bay" : NSLocalizedString("America / Cambridge-Bay", comment: ""),
                "America/Chihuahua"     : NSLocalizedString("America / Chihuahua", comment: ""),
                "America/Ciudad_Juarez" : NSLocalizedString("America / Ciudad-Juarez", comment: ""),
                "America/Costa_Rica"    : NSLocalizedString("America / Costa-Rica", comment: ""),
                "America/Denver"        : NSLocalizedString("America / Denver", comment: ""),
                "America/Edmonton"      : NSLocalizedString("America / Edmonton", comment: ""),
                "America/El_Salvador"   : NSLocalizedString("America / El-Salvador", comment: ""),
                "America/Guatemala"     : NSLocalizedString("America / Guatemala", comment: ""),
                "America/Inuvik"        : NSLocalizedString("America / Inuvik", comment: ""),
                "America/Managua"       : NSLocalizedString("America / Managua", comment: ""),
                "America/Merida"        : NSLocalizedString("America / Merida", comment: ""),
                "America/Mexico_City"   : NSLocalizedString("America / Mexico-City", comment: ""),
                "America/Monterrey"     : NSLocalizedString("America / Monterrey", comment: ""),
                "America/Regina"        : NSLocalizedString("America / Regina", comment: ""),
                "America/Swift_Current" : NSLocalizedString("America / Swift-Current", comment: ""),
                "America/Tegucigalpa"   : NSLocalizedString("America / Tegucigalpa", comment: ""),
                "Pacific/Easter"        : NSLocalizedString("Pacific / Easter", comment: ""),
                "Pacific/Galapagos"     : NSLocalizedString("Pacific / Galapagos", comment: ""),
            ]),

        -25200: GruppedListItem(
            title: "−07:00",
            items: [
                "America/Creston"     : NSLocalizedString("America / Creston", comment: ""),
                "America/Dawson"      : NSLocalizedString("America / Dawson", comment: ""),
                "America/Dawson_Creek": NSLocalizedString("America / Dawson-Creek", comment: ""),
                "America/Fort_Nelson" : NSLocalizedString("America / Fort-Nelson", comment: ""),
                "America/Hermosillo"  : NSLocalizedString("America / Hermosillo", comment: ""),
                "America/Los_Angeles" : NSLocalizedString("America / Los-Angeles", comment: ""),
                "America/Mazatlan"    : NSLocalizedString("America / Mazatlan", comment: ""),
                "America/Phoenix"     : NSLocalizedString("America / Phoenix", comment: ""),
                "America/Tijuana"     : NSLocalizedString("America / Tijuana", comment: ""),
                "America/Vancouver"   : NSLocalizedString("America / Vancouver", comment: ""),
                "America/Whitehorse"  : NSLocalizedString("America / Whitehorse", comment: ""),
            ]),

        -28800: GruppedListItem(
            title: "−08:00",
            items: [
                "America/Anchorage" : NSLocalizedString("America / Anchorage", comment: ""),
                "America/Juneau"    : NSLocalizedString("America / Juneau", comment: ""),
                "America/Metlakatla": NSLocalizedString("America / Metlakatla", comment: ""),
                "America/Nome"      : NSLocalizedString("America / Nome", comment: ""),
                "America/Sitka"     : NSLocalizedString("America / Sitka", comment: ""),
                "America/Yakutat"   : NSLocalizedString("America / Yakutat", comment: ""),
                "Pacific/Pitcairn"  : NSLocalizedString("Pacific / Pitcairn", comment: ""),
            ]),

        -32400: GruppedListItem(
            title: "−09:00",
            items: [
                "America/Adak"   : NSLocalizedString("America / Adak", comment: ""),
                "Pacific/Gambier": NSLocalizedString("Pacific / Gambier", comment: ""),
            ]),

        -34200: GruppedListItem(
            title: "−09:30",
            items: [
                "Pacific/Marquesas": NSLocalizedString("Pacific / Marquesas", comment: "")
            ]),

        -36000: GruppedListItem(
            title: "−10:00",
            items: [
                "Pacific/Honolulu" : NSLocalizedString("Pacific / Honolulu", comment: ""),
                "Pacific/Rarotonga": NSLocalizedString("Pacific / Rarotonga", comment: ""),
                "Pacific/Tahiti"   : NSLocalizedString("Pacific / Tahiti", comment: ""),
            ]),

        -39600: GruppedListItem(
            title: "−11:00",
            items: [
                "Pacific/Midway"   : NSLocalizedString("Pacific / Midway", comment: ""),
                "Pacific/Niue"     : NSLocalizedString("Pacific / Niue", comment: ""),
                "Pacific/Pago_Pago": NSLocalizedString("Pacific / Pago-Pago", comment: ""),
            ]),
    ]

}
